// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package controller

import (
	"{{cookiecutter.project_module_name}}/app/service"
	"{{cookiecutter.project_module_name}}/global/database"
	"{{cookiecutter.project_module_name}}/global/logger"
)

// Injectors from wire.go:

func InitArticleHandler() ArticleHandler {
	db := database.GetDB()
	logrusLogger := logger.GetInstance()
	articleService := service.NewArticleService(db, logrusLogger)
	controllerArticleHandler := NewArticleHandler(articleService)
	return controllerArticleHandler
}
